### PR TITLE
Allow customised Caddy builds

### PR DESCRIPTION
**Pull request by zakcutner**
The ability to use plugins with Caddy and Docker would be a useful feature for me, so I have implemented #25 🎉🎊 I have achieved this by splitting the project into three Dockerfiles, **builder**, **runtime** and **caddy**, and by using [`ONBUILD`](https://docs.docker.com/engine/reference/builder/#onbuild).

**Builder** is similar to before, except it is now in its own Dockerfile. It also now `COPY`s a Go script similar to [this one](https://github.com/caddyserver/caddy/blob/v2/cmd/caddy/main.go) and `RUN`s the Go compiler on it both using `ONBUILD`. This is to allow users to compile their own version of the Go script (at some future build time), *which can importantly include custom plugins*!

**Runtime** is inspired by [Google's Dockerfile for Dart](https://github.com/dart-lang/dart_docker) and provides the environment to run a compiled Caddy binary in (still with the scratch and Alpine variants). It again uses `ONBUILD` to `COPY` resources from **builder**, as again this may have not been built yet due to a user having a custom script.

**Caddy** provides the same Docker image as before: a Caddy binary (in either the scratch or Alpine variant) in the default build with no plugins. However, it uses **builder** and **runtime**, demonstrating how users can create their own script and Dockerfile if they wish for a customised build. It uses a [multi-stage build technique](https://engineering.busbud.com/2017/05/21/going-further-docker-multi-stage-builds/) in order to accomplish this. Due to this technique, buildkit can unfortunately no longer be used [due to a known bug](https://github.com/moby/buildkit/issues/816).

The other alternative I could think of for implementing this would be using build arguments to specify a list of plugins, similar to [another Dockerfile for Caddy](https://github.com/abiosoft/caddy-docker#custom-plugins). However, for me, this is less desirable because it involves modifying the Caddy source code rather than using the [recommended approach](https://github.com/caddyserver/caddy/blob/v2/cmd/caddy/main.go) and allows for less future flexibility.

I have tried my best to update all other files in the repository to work with this new configuration, although there may be some errors. Please let me know if you have any questions or suggested changes!

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Thanks for this, @zakcutner!

I've actually been working (locally, unfortunately no in-progress PR yet) on transforming the build a bit to help get us closer to having a real official build. It's going to be a somewhat major change which will require some changes in this one unfortunately.

I definitely appreciate where you're going with this, and we've had some conversations on how this should work, though nowhere near any kind of consensus yet.

It looks like you've put some considerable effort into this so I hate to discourage you, but I'm not sure we'll be able to merge this without some significant re-work. Usually it's best to discuss the plan before issuing such a significant PR to make sure everyone's on the same page 😅

Can you please give me some time to look through this some more and figure out how best to integrate this with the changes I'm working on? I'll also do my best to issue a PR in the next few days to make it more obvious where the build is headed.

**Comment by zakcutner** [comment]
@hairyhenderson Thanks for getting back to me so quickly! I appreciate all that, I wasn't expecting this to be merged as-is — thank you for offering to take a look.

As there hasn't seemed to be too much interest in my previous issue, I'm mainly just hoping that this will provide some ideas and hopefully accelerate future work on this. Besides, I'll personally probably be using my version in the meantime until something gets implemented so at the least it's useful for me 😄

I really look forward to seeing more of what you've done and hearing your comments on this, just let me know if I can help with anything!

**Comment by hairyhenderson** [comment]
Thanks @zakcutner - I did see #25 but hadn't been able to get to it yet (I've been particularly busy lately).

What may be helpful would be to distill the PR down to _just_ the basic changes required - there are a number of changes that seem unrelated, in the workflow config, the build hook scripts, and some other spots. Also I'm not entirely sure why it was necessary to split the multi-stage build - though I've not had a chance to look closely enough yet so maybe there's a good reason!

**Comment by zakcutner** [comment]
@hairyhenderson no worries at all, I've had a lot of fun doing this!

1. You're right that there are a lot of changes to some of the other config (sorry!), I've tried to do the minimum possible to ensure all the scripts still actually run without errors... most of the added complexity is to do with the multi-stage build.

2. The reason for splitting into a multi-stage build is to allow a custom script to start Caddy to be provided ([as described here](https://github.com/caddyserver/caddy/blob/v2/cmd/caddy/main.go)) rather than the default one with no plugins. I've considered a few ways of achieving this and I went with this method as it seems most similar to how custom builds are created using Caddy normally (without Docker) although I'm definitely open to suggestions and I may well have missed something!

**Comment by zakcutner** [comment]
@hairyhenderson After some thinking, I may have a potential way to reduce the number of Dockerfiles down to two and also to bypass using the method that causes issues with buildkit, whilst providing the same functionality.

However, I think it may be best if I give you a chance to read through my current changes before implementing anything new too see if there is interest in my general approach to generify the Dockerfile into separate `runtime` and `caddy` images.

**Comment by mholt** [comment]
I will leave most of the specifics of how this is accomplished to you guys, but just so you know I think the ability to add plugins to Caddy builds for Docker would be really cool. :+1:

**Comment by hairyhenderson** [comment]
@zakcutner Sorry for the long delay, but the build overhaul is finally done 😅(see #31, and others)

I like the `ONBUILD` idea, and I think what would be best would be to provide a separate tag that users could build from, something like:

```docker
FROM caddy/caddy:v2.0.0-builder

COPY ...
```

I do like the idea of auto-installing lists of modules with build args, but I honestly can't think of a clean way to accomplish that easily.

What could be useful is to provide a script in the builder image that builds a new `main.go` and updates `go.mod`/`go.sum`. I'm thinking of something like:

```docker
FROM caddy/caddy:builder

RUN add-plugin standard, http.prometheus
RUN add-plugin some-other-module
```

What do you think?

**Comment by zakcutner** [comment]
@hairyhenderson Great to hear from you, no problem — it's exciting that so much progress is being made with this. I've been having a think about this and came up with a few things that may be helpful...

1. That's a really interesting idea with having a build script, I hadn't thought of that... if it eliminates the need for the two `ONBUILD` instructions, that could be super useful as it cause a lot of problems! On a related note, whilst I do also like `ONBUILD` as I haven't seen another way to add as much customisability, I have since discovered that it apparently is [no longer being used in official builds](https://github.com/docker-library/docs/pull/911) which may be relevant to achieving an official build.

2. I guess I'm slightly unclear on what the eventual goal of the repo is... aside from using `ONBUILD` images, surely any published image can only ever be for pre-defined Caddy setups? Is the idea that people simply use pre-defined setups from the Docker Hub, or will they clone this repo, customise the build themselves and build their own image? I'm not familiar enough with Caddy to know whether just using the default build is a common use case.

I hope this is useful and thanks again for all your time!

**Comment by hairyhenderson** [comment]
> ... Is the idea that people simply use pre-defined setups from the Docker Hub, or will they clone this repo, customise the build themselves and build their own image?

Yes, to both 😉

I think there's definitely a place for the simple "just let me run a basic site with Caddy" use-case, as well as the "I want to base a more complex site on Caddy" one.

> I guess I'm slightly unclear on what the eventual goal of the repo is

The goal is to become an official image (i.e. `caddy` instead of `caddy/caddy`) - I think we're just about ready to get to that next step, though the main blocker has been my own schedule and health 😅.

I wasn't aware of `ONBUILD` being deprecated in official images, and now that I read through that image I'm reminded of some of the reasons I stopped using it personally quite a while back. I think we can pretty easily achieve everything we want to without using `ONBUILD`.

How about a single command, something like `caddy-build`, that end users can use to build a custom Caddy image? We could also encourage multi-stage images for this to reduce size. Something like:

```docker
FROM caddy/caddy:v2.0.0-builder AS builder

RUN caddy-build --plugins foo,bar,baz

FROM caddy/caddy:v2.0.0 AS runtime

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY Caddyfile /etc/caddy/Caddyfile
COPY site/ /usr/share/caddy
```

This particular approach would use the existing `caddy/caddy` image with all of its configuration (including certs, `VOLUME`s for `/data` and `/config`, and a few other things), and simply replace the binary and `Caddyfile`.

In this case, the `caddy-build` script would:
- create a new `main.go` somewhere, 
- add in the requested plugins
- run `go mod init caddy`
- run `go build -o /usr/bin/caddy`

This doesn't seem too complex TBH. I'll whip something up and see how useful it is.

**Comment by hairyhenderson** [comment]
Yup, pretty straightforward:

```shell
#!/bin/sh
plugins=$@

mkdir -p /src/custom-caddy/cmd/caddy
cd /src/custom-caddy/cmd/caddy

cat >> main.go <<EOF
package main

import (
	caddycmd "github.com/caddyserver/caddy/v2/cmd"
	_ "github.com/caddyserver/caddy/v2/modules/standard"
EOF

for p in $plugins; do
    echo -e "\t_ \"$p\"" >> main.go
done

cat >> main.go <<EOF 
)

func main() {
	caddycmd.Main()
}
EOF

cat >> go.mod <<EOF
module caddy

go 1.14

require (
	github.com/caddyserver/caddy/v2 v2.0.0-beta.15
)
EOF

CGO_ENABLED=0 go build -trimpath -tags netgo -ldflags '-extldflags "-static" -s -w' -o /usr/bin/caddy
```

This is then usable like:

```Dockerfile
FROM caddy/caddy:builder AS builder

RUN caddy-builder \
    github.com/caddyserver/nginx-adapter \
    github.com/hairyhenderson/caddy-teapot-module

FROM caddy/caddy

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

@zakcutner what do you think?

**Comment by zakcutner** [comment]
@hairyhenderson Yes, I definitely agree that this is better... it also has the nice advantage that if you want to directly specify your `main.go` you could just completely bypass the builder image (and `caddy-build` script) too.

As a really small point, maybe it's nicer to use a `--plugins` flag like in your original example as perhaps there are other types of customisability aside from adding plugins that may be useful in the future? Alternatively, your original idea for multiple commands (e.g. `add-plugin`) would solve this as well.

Looks great though — super cool idea!

**Comment by hairyhenderson** [comment]
@zakcutner ok - want me to update this PR with the code I've got?

**Comment by hairyhenderson** [comment]
oh and, about `--plugins`, after messing around for a bit I realized that parsing args in a shell script is super awkward, and in this case not really necessary. What's nice about the single `caddy-builder` script is that it's the only command necessary to do the whole build.

I kinda feel like any extra functionality should be just left as an exercise to the end-user. It's always possible to just use the builder image as a simple way to get all the source and build environment for Caddy, and ignore the rest 😉

**Comment by zakcutner** [comment]
@hairyhenderson Fair enough, I guess if it's the only thing that the script is used for at the moment it makes calling it a bit shorter too.

> @zakcutner ok - want me to update this PR with the code I've got?

Yeah that would be great thanks, I think you should be able to edit this PR but let me know if there is a problem... feel free to force push over my original changes.

**Comment by hairyhenderson** [comment]
oops - messed up that push 😂 - will try to reopen

**Comment by hairyhenderson** [comment]
nuts, that failed. @zakcutner - looks like your using `master` is causing some issues.. I'm going open a continuation in a new PR.

**Comment by zakcutner** [comment]
@hairyhenderson No worries, that's okay!

**Pull request closed without merging**
