### PR TITLE
Using non root user

### PR DESCRIPTION
**Pull request by Ilyes512**
- [x] added EXPOSE labels https://github.com/caddyserver/caddy-docker/issues/1
- [x] Fixed Taskfile
- [x] Create caddy user and use that for running caddy unprivileged 
- [x] Add volume
- [ ] ~~Write some examples/intructions https://github.com/caddyserver/caddy-docker/issues/11~~ will be done in a different branch

The original PR and branch can be found here: https://github.com/caddyserver/caddy-docker/pull/6 Since there were allot of changes I created a new branch and PR.

### CODE REVIEW

**Comment by hairyhenderson** [comment]
@Ilyes512 Is there a reason you deleted the `.dockerignore` file? That's a useful one to prevent unnecessary files being copied into the build context...

**Comment by Ilyes512** [comment]
(Ow wtf... did not receive a email about your reply - only noticed it after checking out some boxes)

The reason is because I think the few KB's extra that it would need to send to the build context is not going to be noticeable. I can add it back.

**Comment by hairyhenderson** [comment]
@Ilyes512 I'm not sure I understand why you added another `docker-entrypoint.sh` script in f0d0686180a225f98edcd62a0123f372390a27e8 - how is that related to the volume thing?

**Comment by Ilyes512** [comment]
Not sure if this is the best solution, but the reason is to overwrite the `/etc/caddy/Caddyfile` using a (host)volume.

The original CMD was:

```
CMD [ "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile" ]
```

The only way to overwrite the Caddyfile is by creating a new image and using `COPY`.

If you use an entrypoint script... any possible volumes will already have been mounted.

**Comment by hairyhenderson** [comment]
@Ilyes512 I'm not sure why the two are related though, if you mount a new `/etc/caddy/Caddyfile` into the container with a volume, using `CMD` works just fine.

**Comment by Ilyes512** [comment]
After @hairyhenderson's double-check and my own check the commit that added the entrypoint file has been reverted.

**Comment by hairyhenderson** [comment]
> - [ ] Write some examples/intructions

@Ilyes512 I think this piece ⬆️ could probably go in a separate PR. This one's good to go, and we'll be able to get a good image built sooner 😉

**Comment by Ilyes512** [comment]
@hairyhenderson you may merge it :)

**Pull request merged**
