### PR TITLE
Caddy v2.7.0

### PR DESCRIPTION
**Pull request by hairyhenderson**
Caddy 2.7 is out! https://github.com/caddyserver/caddy/releases/tag/v2.7.0

Also removes the 2.6 build

### CODE REVIEW

**Review by francislavoie — APPROVED** [review]

**Comment by francislavoie** [comment]
Hold off for the moment https://github.com/caddyserver/caddy/issues/5671

**Comment by mholt** [comment]
2.7.1 has been tagged.

**Comment by mholt** [comment]
Dangit, 2.7.2 has been tagged and this one actually works as far as we can tell. Sorry :upside_down_face:

**Comment by faradaytrs** [comment]
> 

could we push 2.7.2 to docker hub?

**Comment by hairyhenderson** [comment]
@faradaytrs it's coming...

**Comment by hairyhenderson** [comment]
Superseded by #306

**Pull request closed without merging**
