### PR TITLE
Fix broken README links

### PR DESCRIPTION
**Pull request by jkuester**

### CODE REVIEW

**Comment by francislavoie** [comment]
Thanks!

**Comment by francislavoie** [comment]
Ah whoops - I forgot to check that you made the change in both files - we have a README.md.tmpl which generates the README.md because we want to keep the tagged containers updated. I made a separate commit to update the template with your change as well https://github.com/caddyserver/caddy-docker/commit/253ddff35ce9e7a1562356156172f0a496273a10

**Comment by hairyhenderson** [comment]
Thanks @jkuester and @francislavoie! I'll need to update https://github.com/docker-library/docs/pull/1667/ too 😉

**Comment by hairyhenderson** [comment]
Ok, updated in https://github.com/docker-library/docs/pull/1667/commits/70c6f4054e1184fdc6558d8d703b787072a9487b

**Pull request merged**
