### PR TITLE
Caddy v2.6.0-beta.5

### PR DESCRIPTION
**Pull request by hairyhenderson**
https://github.com/caddyserver/caddy/releases/tag/v2.6.0-beta.5

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by mholt** [comment]
Thanks Dave!

I forgot to mention, this was mostly a test of our CI. I'll probably tag the stable next week.

**Comment by hairyhenderson** [comment]
@mholt ah - it's no trouble to create a new image... or do you want to just wait for 2.6.0 proper?

**Comment by mholt** [comment]
It's up to you, it just might only be the lastest for a few days maybe a week. I support it either way if it's not a lot of work! Just wanted to let you know so you could gauge things.

**Comment by hairyhenderson** [comment]
ok! I've done this much, it's only another 2mins of work to finish it - mind approving it? 😁

**Review by francislavoie — APPROVED** [review]

**Pull request merged**
