### PR TITLE
ci: Set up release tagged job

### PR DESCRIPTION
**Pull request by francislavoie**
Replaces #79

We need the PR to be on a branch in this repo so we can test making MRs from the github actions.

### CODE REVIEW

**Comment by francislavoie** [comment]
@hairyhenderson 

sad

Can't run the create PR action in your container without some additional deps :'(

**Comment by hairyhenderson** [comment]
@francislavoie ah - looks like `peter-evans/create-pull-request@v2` is built for Node.js (which this particular image doesn't include).

I'll take a look later today 😉

**Comment by francislavoie** [comment]
Also looks like it uses python?

**Comment by hairyhenderson** [comment]
> the only reason we need your image here is to run `make` with `gomplate`

That's easy to install on the base VM then - `curl -SLo /usr/local/bin/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.6.0/gomplate_linux-amd64-slim` should do the trick.

**Comment by hairyhenderson** [comment]
(and `make` should be present in the base VM already)

**Comment by francislavoie** [comment]
Alright now we just need to tweak how the PR looks instead of using the defaults. See #85

**Pull request merged**
