### PR TITLE
Caddy v2.6.3

### PR DESCRIPTION
**Pull request by hairyhenderson**
https://github.com/caddyserver/caddy/releases/tag/v2.6.3

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Review by francislavoie — APPROVED** [review]

**Comment by luzfcb** [comment]
Wow, we finally have v2.6.3.
Thanks for the hard work.
That said, what's the ETA for the 2.6.3 version to be available on the docker hub?

**Comment by mholt** [comment]
It's usually a few business days. Depends on how busy they are over there, I think :)

**Comment by luzfcb** [comment]
It's weird, now I see 2.6.3-alpine in docker hub, but still not able to pull it.

```bash
❯ docker compose -f caddy.yml build
[+] Building 0.5s (3/3) FINISHED                                                                                                                                                             
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 248B                                                                                                                                                       0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 631B                                                                                                                                                    0.0s
 => ERROR [internal] load metadata for docker.io/library/caddy:2.6.3-alpine                                                                                                             0.5s
------
 > [internal] load metadata for docker.io/library/caddy:2.6.3-alpine:
------
failed to solve: caddy:2.6.3-alpine: no match for platform in manifest sha256:e782cdc152609a801ac266b687d8edf04ba03afcc79feab6b893b3cf70e58b25: not found


❯ docker pull caddy:2.6.3-alpine 
2.6.3-alpine: Pulling from library/caddy
no matching manifest for linux/amd64 in the manifest list entries

```

Maybe the CI is still running and hasn't published the image to `linux/amd64` yet.
I will try again in 1 hour.

**Comment by francislavoie** [comment]
Official docker library images get built by their Jenkins CI server. It can take some time, since it's competing with resources with every other official image being built.

**Pull request merged**
