### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by k2589**
Reverse proxy to container without attaching  to container's  network

### CODE REVIEW

**Comment by francislavoie** [comment]
I'm not a fan of recommending that in the README. Doing that throws away most of the network security that Docker provides. In addition, this doesn't really have much to do with running _Caddy_ in Docker, but more of a general example for any networked container.

I do think there's value in having a docker-compose example in the README, but I don't think this is it.

**Comment by mholt** [comment]
Could consider using the wiki for these kinds of things, too.

**Comment by hairyhenderson** [comment]
Thanks for the contribution @k2589, but I agree with @francislavoie, this doesn't really belong in this document.

Perhaps a short blurb in the wiki on why someone might want this would be useful, as well as a link to the appropriate Docker documentation?

**Comment by k2589** [comment]
@hairyhenderson I'm also agree with Francis:) 
Is it Wiki working right now? Doesn't get anything on click on it)

**Comment by mholt** [comment]
@k2589 I just created the first page, will it not let you add new pages?

Anyway, feel free to edit that first page I guess!

**Comment by k2589** [comment]
@mholt Thank you! It's working:)

**Comment by k2589** [comment]
I added page 'Specific user cases' and this PR subject into it.

**Pull request closed without merging**
