### PR TITLE
Generating Dockerfiles for Caddy 2.0 and 2.1 images

### PR DESCRIPTION
**Pull request by hairyhenderson**
Supersedes #93 

Introduces an extra top layer of versioned directories.

Also instead of generating each `Dockerfile` individually, that's now done by a single rendering template. It makes the generation a bunch faster too.

This also adds the ability to mark a specific image as the "major" version (i.e. should have the `2`, `2-alpine`, etc tags & shared tags), and as the "latest" version (i.e. should have the `latest`, `alpine`, etc tags & shared tags).

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by mholt** [comment]
Wow, awesome. I don't need to update these instructions right? https://caddyserver.com/docs/download#docker

**Comment by hairyhenderson** [comment]
@mholt nope! this is status-quo for the current images, and just adds some new ones with the beta tags. Once 2.1 is released, the appropriate tags will be updated too.

**Comment by francislavoie** [comment]
Yeah sorry I never got around to reviewing this.

So is the plan to only keep the `2.0` dir as long as `2.0` is supported? FWIW I highly doubt we'll make patch fixes for `2.0` at this point (if we would've made any it would've been in the past 5 weeks before this beta)

**Comment by hairyhenderson** [comment]
> So is the plan to only keep the `2.0` dir as long as `2.0` is supported?

I'll defer that to @mholt, but _at least_ while 2.1's in beta we need to continue to support 2.0 😉- note that even though Caddy itself may not get patched, it's still useful to have the tags listed in DockerHub and to have the base images automatically updated for us.

**Comment by mholt** [comment]
As long as it's not the latest minor version, I'm indifferent. Is there really any value of keeping 2.0 around once we're into the 2.1 tree? (And if people still really need 2.0 for some reason, couldn't they just build their own?)

Generally I prefer simpler/less. But I'll leave it up to you!

**Comment by francislavoie** [comment]
Yeah I think it makes sense to just keep N and N-1 around, don't really need more than that though.

**Comment by hairyhenderson** [comment]
Ok, merging then so we can get the Caddy 2.1 beta images going 😉

**Pull request merged**
